### ISSUE TITLE
Error at the beginning - 'unable  to open X server' and 'command not found'

### ISSUE THREAD

**Issue by naturepoker** [susiegriggo/Phynteny#3]
Hi, 

I'm running into an error message at the beginning of a run, after which Phynteny promptly quits. 

I'm trying Phynteny out on a Pharokka annotated gbk file using a remote machine via terminal SSH (Xeon, Ubuntu 22.04.02).

Phynteny is installed in its own conda environment (python version 3.9.1) create with:
```
conda create -n phynteny python=3.9.0
conda activate phynteny
mamba install -c conda-forge scikit-learn=1.2.2
mamba install -c conda-forge pandas=2.0.2
mamba install -c conda-forge biopython=1.81
mamba install -c conda-forge numpy=1.21.0
mamba install -c conda-forge tensorflow=2.9 

git clone https://github.com/susiegriggo/Phynteny.git --branch no_unknowns --depth 1
cd Phynteny
python -m pip install .
```

Command used and resulting error message is:

```
phynteny pharokka_genome/pharokka_genome.gbk -o test
/home/miniconda3/envs/phynteny/bin/phynteny: line 5: $'\nPhynteny: synteny-based annotation of phage genes\n': command not found
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
/home/miniconda3/envs/phynteny/bin/phynteny: line 11: from: command not found
/home/miniconda3/envs/phynteny/bin/phynteny: line 12: from: command not found
/home/miniconda3/envs/phynteny/bin/phynteny: line 13: from: command not found
/home/miniconda3/envs/phynteny/bin/phynteny: line 14: from: command not found
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
/home/miniconda3/envs/phynteny/bin/phynteny: line 17: __author__: command not found
/home/miniconda3/envs/phynteny/bin/phynteny: line 18: __maintainer__: command not found
/home/miniconda3/envs/phynteny/bin/phynteny: line 19: __license__: command not found
/home/miniconda3/envs/phynteny/bin/phynteny: line 20: __version__: command not found
/home/miniconda3/envs/phynteny/bin/phynteny: line 21: __email__: command not found
/home/miniconda3/envs/phynteny/bin/phynteny: line 22: __status__: command not found
/home/miniconda3/envs/phynteny/bin/phynteny: line 26: syntax error near unexpected token `@click.argument'
/home/miniconda3/envs/phynteny/bin/phynteny: line 26: `@click.argument("infile", type=click.Path(exists=True))'
```

I'm too much of a linux newbie to figure this out myself, but please feel free to let me know if you need anything!

**Comment by susiegriggo** [comment]
Thanks for testing Phynteny and being the first person to log an issue! 

I think this was an issue in the main phynteny script which I've now fixed (hopefully) and pushed. Would you be able to pull the repo and try again? 

```
cd Phynteny
git pull 
pip install . 
```

Just as an aside, when you install Phynteny, all of the dependencies (scikit-learn, pandas, biopython, numpy and tensorflow) will be installed with it meaning that you don't need to install them with mamba beforehand. 

If that doesn't work please let me know!

**Comment by naturepoker** [comment]
Hi, 

Thank you for the very prompt response.

I did the git pull and re-installation, and everything works perfectly now. So far it's annotated 6 new genes in two phage genomes. I'll probably end up throwing in some putative prophage genomes that's been bothering me for the last year too - exciting stuff!

There is another behavior that might be worth noting though - just as a sanity check I created another conda environment (with python 3.9.0 as described before) and installed Phynteny in it without the manual mamba steps. Phynteny installation in that particular environment seems to quit during gbk reading step with below traceback: 

```
Traceback (most recent call last):
  File "/home/miniconda3/envs/test-phynteny/bin/phynteny", line 120, in <module>
    main()
  File "/home/miniconda3/envs/test-phynteny/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/miniconda3/envs/test-phynteny/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/miniconda3/envs/test-phynteny/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/miniconda3/envs/test-phynteny/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/miniconda3/envs/test-phynteny/bin/phynteny", line 89, in main
    gene_predictor = predictor.Predictor(
  File "/home/miniconda3/envs/test-phynteny/lib/python3.9/site-packages/phynteny_utils/predictor.py", line 210, in __init__
    self.confidence_dict = get_dict(confidence_dict)
  File "/home/miniconda3/envs/test-phynteny/lib/python3.9/site-packages/phynteny_utils/predictor.py", line 30, in get_dict
    dictionary = pickle.load(handle)
AttributeError: Can't get attribute 'EuclideanDistance' on <module 'sklearn.metrics._dist_metrics' from '/home/miniconda3/envs/test-phynteny/lib/python3.9/site-packages/sklearn/metrics/_dist_metrics.cpython-39-x86_64-linux-gnu.so'>
```
I'm not sure what the difference between the two might be - attaching pip list output from old environment (installation with mamba) and new environment (blank environment with phynteny install).

As a test I also ran the two different installation methods directly on my laptop (running same Ubuntu LTS version as the workstation). The environment with manual mamba dependency install seems to work, but the other one with just Phynteny pip install halts with the same traceback message. 

Sorry to respond to a solution with another issue, just thought this might be worth a note. 
  
[new_phynteny_pip_list.txt](https://github.com/susiegriggo/Phynteny/files/11996605/new_phynteny_pip_list.txt)
[old_phynteny_pip_list.txt](https://github.com/susiegriggo/Phynteny/files/11996606/old_phynteny_pip_list.txt)

**Comment by susiegriggo** [comment]
I'm glad that Phynteny worked on your phages!  Hopefully, it finds some genes for your prophages as well. 

Thanks for sending the additional issue through, it looks like version 1.3.0 of sklearn has some differences from version 1.2.2 that I wasn't aware of. I've now restricted the setup file to install version 1.2.2 only so that it should work just by installing it using pip. I'll try to expand this to more versions once I figure out which ones do and don't work.

**Comment by naturepoker** [comment]
Well noted, thank you so much for the help!

I'll close this issue for now since the main question's been resolved.
